### ISSUE TITLE
[Mage:Fire] Headmaster's Will is not found to add it to a Custom List

### ISSUE THREAD

**Issue by FedericoGregori** [lgallucci/LoonBestInSlot#29]
Headmaster's Will is not found to add it to a Custom List

Using latest version of the Addon y Official MoP Classic

<img width="883" height="564" alt="Image" src="https://github.com/user-attachments/assets/55e49d0e-99e4-4d36-80c4-66160ad853db" />

**Comment by lgallucci** [comment]
Should be fixed in 6.1.4

**Comment by FedericoGregori** [comment]
Hi, still not working for me. Should I delete cache or something similar?

**Comment by lgallucci** [comment]
Make sure you've updated to the latest version.... deleting local addon data will remove all your custom lists data.

You should see the text "LBIS: Clearing Cache" when you start up after updating the addon.  That will tell you that it worked.

If none of that works, deleting the file "World of Warcraft/_classic_/WTF/Account/ACCOUNT_NAME/SavedVariables/LoonBestInSlot.lua" should reset the cache manually.

**Comment by FedericoGregori** [comment]
Deleting LoonBestInSlot.lua solved. Thanks a lot for your effort!
